"""add_google_sync_ids

Revision ID: 6faf8196f248
Revises: eebd7511972d
Create Date: 2026-08-04 21:18:05.636947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6faf8196f248'
down_revision: Union[str, Sequence[str], None] = 'eebd7511972d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('google_event_id', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('google_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'google_task_id')
    op.drop_column('events', 'google_event_id')
    # ### end Alembic commands ###
